/*
 * SpiderGUI.java
 *
 * Created on 18. Juni 2005, 21:53
 */

package com.bensmann.superframe.beta.webspider;

/**
 *
 * @author  Ralf Bensmann
 */
public class SpiderGUI extends javax.swing.JFrame {
    
    /**
     * Creates new form SpiderGUI
     */
    public SpiderGUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        settingsPanel = new javax.swing.JPanel();
        httpLabel = new javax.swing.JLabel();
        urlTextField = new javax.swing.JTextField();
        fileTypeCombobox = new javax.swing.JComboBox();
        grabButton = new javax.swing.JButton();
        maxThreadsTextField = new javax.swing.JTextField();
        progressPanel = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        settingsPanel.setOpaque(false);
        settingsPanel.setPreferredSize(new java.awt.Dimension(615, 70));
        httpLabel.setText("http://");
        settingsPanel.add(httpLabel);

        urlTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        urlTextField.setText("www.");
        urlTextField.setMinimumSize(new java.awt.Dimension(6, 50));
        urlTextField.setPreferredSize(new java.awt.Dimension(360, 20));
        settingsPanel.add(urlTextField);

        fileTypeCombobox.setOpaque(false);
        fileTypeCombobox.setPreferredSize(new java.awt.Dimension(80, 22));
        settingsPanel.add(fileTypeCombobox);

        grabButton.setText("Grab");
        grabButton.setToolTipText("Go and grab specified file types from URL");
        settingsPanel.add(grabButton);

        maxThreadsTextField.setText("jTextField1");
        settingsPanel.add(maxThreadsTextField);

        getContentPane().add(settingsPanel, java.awt.BorderLayout.NORTH);

        jProgressBar1.setPreferredSize(new java.awt.Dimension(550, 16));
        progressPanel.add(jProgressBar1);

        getContentPane().add(progressPanel, java.awt.BorderLayout.SOUTH);

        jTextPane1.setPreferredSize(new java.awt.Dimension(100, 20));
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpiderGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox fileTypeCombobox;
    private javax.swing.JButton grabButton;
    private javax.swing.JLabel httpLabel;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField maxThreadsTextField;
    private javax.swing.JPanel progressPanel;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JTextField urlTextField;
    // End of variables declaration//GEN-END:variables
    
}
